BUNDLE_NAME := WindowPlaner
WindowPlaner_OBJC_FILES = WindowPlaner.m

WindowPlaner_INSTALL_PATH = /System/Library/PreferenceBundles

WindowPlaner_FRAMEWORKS = UIKit
WindowPlaner_PRIVATE_FRAMEWORKS = Preferences

include ../framework/makefiles/common.mk
include ../framework/makefiles/bundle.mk
